name: 'please-write-ignore-reason'
description:
  'This action will check your static code analysis files to see if they have a
  reason for ignoring a rule.Currently, this action supports only Brakeman.'
author: 'bun913'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  fileListString:
    description: 'Comma separated list of files to check'
    required: true
    default: './brakeman.ignore'

# Define your outputs here.
outputs:
  result:
    description: 'Check result'

runs:
  using: node20
  main: dist/index.js
