name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          fileListString: 'src/modules/brakeman/__test__/valid.json,src/modules/brakeman/__test__/valid2.json'

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.result }}"

      - name: Failed beauce of including no-note file
        id: failed-action
        uses: ./
        with:
          fileListString: 'src/modules/brakeman/__test__/valid.json,src/modules/brakeman/__test__/noNote_brakeman.ignore.json'
        continue-on-error: true

      - name: Failed beauce of including no-exist file path
        id: failed-action-no-file
        uses: ./
        with:
          fileListString: 'no_exist_file.json,src/modules/brakeman/__test__/noNote_brakeman.ignore.json'
        continue-on-error: true
